#include "game-of-life.h"

#include <unistd.h>

int main(void)
{
	cell grid[] = {
		DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	ALIVE,	ALIVE,	ALIVE,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	ALIVE,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	ALIVE,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	ALIVE,	ALIVE,	ALIVE,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	ALIVE,	ALIVE,	ALIVE,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	ALIVE,	ALIVE,	ALIVE,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	ALIVE,	ALIVE,	ALIVE,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	ALIVE,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	ALIVE,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	ALIVE,	ALIVE,	ALIVE,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,
		DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,	DEAD,
	};

	Game_of_life *game = create_game(grid, 18, 11);

	print_game(game);
	while(1) {
		sleep(1);
		turn(game);
		print_game(game);
	}

	return 0;
}
